unjs/pathe

src/index.ts
This takes advantage of the fact that win32 handles both `\` and `/` as valid separators and therefore can operate safely on a posix path.
1. resolves #2 by using `path.win32` (resolve)
1. handles unc paths by using `path.win32` (join)
1. resolves a parse issue where the drive letter was being stripped on windows
1. normalizes `toNamespacedPath` as well, for consistency
**An observation**: this entire library works (passes tests) in reverse using `path.win32` and normalising the result (as with 1 & 2 above)
With this PR merged, #3 should be passing.
=> fix: use platform dependent path for `join`, `resolve`, and `parse`

.eslintrc, .github/workflows/ci.yml, .gitignore, LICENSE, README.md, package.json, src/index.ts, src/path.ts, src/utils.ts, test/index.spec.ts, tsconfig.json, yarn.lock
This flags a few issues which I'll submit a separate PR for (#4)
**note**: I took inspiration from node docs rather than upath, but will go back and fill in any missing areas.
resolves #1
=> feat: improved implementation with tests

.github/workflows/ci.yml, package.json, src/index.ts, src/path.ts, test/index.spec.ts, yarn.lock
This PR adopts minimal implementations of `path` functions that were previously missing (as well as a vitest implementation).
I'll take a second pass on this later to add some complexity back in.
The only intended change in behaviour is that we now parse windows paths to a root of the drive letter (e.g. `C:`), which resolves #5.
=> feat!: implement rest of `path` minimally 

src/path.ts, test/index.spec.ts
=> fix: return `.` as dirname fallback for non-absolute paths

src/path.ts, test/index.spec.ts
The tests added are all default Node behaviour.
resolves #16
=> fix: replace double-slashes in `join` calls

src/path.ts, test/index.spec.ts
=> fix: normalize `process.cwd` on windows

.github/workflows/ci.yml, build.config.ts, package.json, src/_internal.ts, src/path.ts, src/utils.ts, test/index.spec.ts, test/utils.spec.ts, tsconfig.json
=> feat: add `normalizeAliases` and `filename` in `/utils` subpath

src/path.ts
=> fix: `process.cwd` fallback on non-node env

src/path.ts, src/utils.ts, test/index.spec.ts
resolves https://github.com/unjs/pathe/issues/126
The `split` method will generate redundant `""` when pass a root path
https://github.com/unjs/pathe/blob/055f50a6f1131f4e5c56cf259dd8816168fba329/src/path.ts#L213-L215
```ts
"/".split("/") //=> ["", ""] 
// But expected [""]
```
=> fix: trim root folder `/` when calculating relative paths

src/path.ts
Fixes #148
Some runtimes (like React Native) has a `process` global, but doesn't provide a `cwd` function. Instead of assuming the `cwd` function is available, just because the `process` global is, merging this PR will update the check to actually verify the `process.cwd` is a callable function before relying on it.
Resolves #148
=> fix: check `process.cwd` before calling it

src/_internal.ts, src/path.ts, test/index.spec.ts
resolves https://github.com/nuxt/nuxt/issues/24621
It was possible for a path segment to mismatch (`c:` !== `C:`) owing to drive letter case. This normalises it in `relative` before splitting into segments.
I can update this if https://github.com/unjs/pathe/pull/142 merges first.
=> fix: uppercase windows drive letters

src/utils.ts, test/utils.spec.ts
resolve #154
Hi :wave: this PR fix `resolveAlias`'s pathSeperator check by verifying if the alias ends with `/` or `\`
=> fix(resolveAlias): handle aliases ending with trailing slash

src/path.ts, test/index.spec.ts
resolves #143
Small note: While current fix seemed reasonable to me, I am also amazed that `resolve` function internally makes paths like `/C:/` perhaps with some better fixes of route cause workaround like this and #142 wouldn't be required..
=> fix(relative): handle different windows drive letters

package.json
This is needed for TypeScript project to load the ESM code.
Resolves #191
=> build: add `type: module` to `package.json`

src/path.ts, src/utils.ts
Added JSDocs to functions and consts that are exported from the lib
> Any feedback is welcomed! 🙌
=> docs: add jsdocs for `pathe/utils`

src/path.ts, test/index.spec.ts
=> fix(basename): ignore trailing seperator

src/utils.ts, test/utils.spec.ts
(#184)
This change resolves the issue reported with files containing no extension. It also adds tests for filenames such as `.gitignore` or `.env` which begin with a period.
=> fix(utils/filename): handle files beginning with a period or without ext

package.json
Check PR title
Current version:
With this PR:
=> build: update exports

src/index.ts
=> feat: add `posix` and `win32` exports to match `node:path`

src/path.ts, test/index.spec.ts
resolves #167
Rework of #168 by @prisis
`root` in `parse` result should be strictly either `/` or `X:/` (as per node util docs)
This PR:
- Removes `.` fallback for posix paths
- Adds trailing `/` to win32 paths
---
```js
import path from 'node:path'
import pathe from 'pathe'
console.log('Node version: ' + process.version + "\n");
for (const p of [".\\dir\\file", "C:\\path\\dir\\file.txt"]) {
console.log(p);
console.log("   path  (posix)  : ", JSON.stringify(path.posix.parse(p)));
console.log("   path  (win32)  : ", JSON.stringify(path.win32.parse(p)));
console.log("   pathe (new)    : ", JSON.stringify(pathe.parse(p)));
console.log();
}
```
=> fix(parse)!: fix root handling to be consistent with node

src/path.ts, test/index.spec.ts
**Reference:** #175 
This pull request fixes the issue where the delimiter is a colon (:) on all platforms, including Windows where it should use a semicolon (;).
=> feat!: set `delimiter` to `;` in windows

test/index.spec.ts
Node behavior for extname("file.tar.gz") is `.gz`
Adding tests to make sure pathe can handle that
=> test: add additional tests for `extname`

src/path.ts, test/index.spec.ts
resolves #178 (https://github.com/unjs/pathe/issues/178#issuecomment-2328147213)
Even though `normalize` is UNC aware, `join` utility blindly strips the leading UNC indicator with a final replacement.
This PR changes `join` implementation to avoid global regex (normalize finally takes care of proper normalization).
Note: While all existing tests pass, this is a potential behavior change
Note: This PR does **not** add URL compatibility to path utils as it needs changes to more utils and it is out of scope / non goal.
=> fix(join)!: preserve normalized unc paths

.github/workflows/ci.yml, README.md, src/utils.ts, test/utils.spec.ts
Create a reverse lookup to resolve an absolute path towards the aliased path
Created an extra util which allows the user to lookup the alias path from the aliases. Pretty much reverting the `resolveAlias` method. Personal use case is creating some linting rules within Nuxt towards explicit imports using the aliases. Other angles are appreciated
=> feat(utils): add `reverseResolveAlias` util

src/_path.ts, src/index.ts, src/utils.ts, test/index.spec.ts
In #176 (2.0) we have introduced `posix` and `win32` top level exports to match exact `node:path` exports as drop-in replacement. 
However it wans't matching runtime behavior (found during unenv upgrade). `path.posix.win32` can be chained.
This PR also fixes the issue that `pathe.posix.delimiter` is always set to `:` now + allows strict treeshaking (with esbuild)
=> fix: mixed `posix`/`win32` namespaces

src/index.ts
Regression of #197, `pathe` export types should now be identical to `node:path`
=> fix: use `node:path` export types

src/_path.ts, src/index.ts, src/utils.ts, test/index.spec.ts, test/utils.spec.ts, tsconfig.json
Enables most of what's in the unjs tsconfig template, plus the following:
- `noUnusedLocals`
- `noUnusedParameters`
i didn't take the entire unjs template because it'd mean changing the module/moduleResolution/moduleDetection
@pi0 almost all of the casts are because `noUncheckedIndexedAccess` is true. we can turn it off if you think we will do that quite often (e.g. when we check length of something, we know it then has `[0]` but typescript doesn't)
=> chore: enable strict typescript compilation

src/_path.ts, test/index.spec.ts
Hi, I want to use `pathe` in @rollup/pluginutils to support browser environments. https://github.com/rollup/plugins/pull/1838
But some [tests](https://github.com/rollup/plugins/blob/d64f8d69d0ca138161fc98c0b2cd2b5df73c2895/packages/pluginutils/test/addExtension.ts#L15) are failing, so I created this PR.
=> fix(extname): handle inputs ending with dot
